import { Materiel } from './materiel';
export const MATERIELS : Materiel [] =  [
        { id : 1 ,
          nom : 'TAPIS ROULANT ZIMOTA -NOIR & ROUGE- (1040)',
          prix :1249000 , 
          image : 'assets/tapis-roulant-zimota-noir-rouge-1040-tunisiee.jpg'} ,
        { id : 2 ,
            nom : 'TAPIS DE COURSE ZIMOTA 2500',
            image : 'assets/tapis-de-course-zimota-2500-tunisiee.jpg' ,
            prix:1849000 } ,
        { id : 3 ,
            nom : 'BANC DE MUSCULATION PLIABLE EVERFIT (WBK-500)',
            image : 'assets/banc-de-musculation-pliable-everfit-wbk-500-tunisiee.jpg' ,
            prix:369000 } ,
        {id : 4 ,
             nom : 'HAMMER 4507',
            image : 'assets/HAMMER 4507.png' ,
            prix: 619000 } ,
        { id : 5 ,
            nom : 'velo-elliptique-chrono-line-toorx-erx-100-tunisie.',
            image : 'assets/velo-elliptique-chrono-line-toorx-erx-100-tunisie..jpg' ,
           prix: 1659000 } ,
        { id : 6 ,
            nom : 'ECOSTEP + 2 RÉHAUSSES VRAC SVELTUS - NOIR (0281)',
            image : 'assets/ECOSTEP + 2 RÉHAUSSES VRAC SVELTUS - NOIR (0281).png' ,
            prix: 115000 } ,
        { id : 7 ,
            nom : 'PAIRE DE DISQUES 2X0.5 KG -HAMMER- ( 4664)',
            image : 'assets/PAIRE DE DISQUES 2X0.5 KG -HAMMER- ( 4664).png' ,
            prix: 16000 } ,
        { id : 8 ,
            nom : 'balle-lest--e-bleue-500g--svel',
            image : 'assets/balle-lest--e-bleue-500g--svel.png' ,
            prix: 23000  } ,
        { id : 9 ,
            nom : 'RESSORT DE BARRE MUSCULATION (DIA30)',
            image : 'assets/RESSORT DE BARRE MUSCULATION (DIA30).png' ,
            prix:  3900} 
      ]
